[package]
name = "repo-manage-util"
version = "0.1.1"
authors = ["Vladislav Nepogodin <vnepogodin@cachyos.org>"]
edition = "2021"
description = "A command-line utility for managing Arch Linux repositories"
license = "GPL-3.0-or-later"

[dependencies]
alpm = { version = "4", features = ["checkver"], default-features = false }
anyhow = { version = "1", default-features = false, features = ["std"] }
clap = { version = "4.5", features = ["derive"] }
glob = "0.3"
log = "0.4"
rand = { version = "0.9", features = ["std", "std_rng", "thread_rng"], default-features = false }
serde = { version = "1", features = ["derive"] }
subprocess = "0.2"
toml = "0.8"

[profile.release]
strip = "symbols"
panic = "abort"
lto = true
opt-level = 3
codegen-units = 1
