[package]
name = "repo-manage-util"
version = "0.3.0"
authors = ["Vladislav Nepogodin <vnepogodin@cachyos.org>"]
edition = "2024"
description = "A command-line utility for managing Arch Linux repositories"
license = "GPL-3.0-or-later"

[dependencies]
alpm = { version = "5", features = ["git"], default-features = false }
anyhow = { version = "1", default-features = false, features = ["std"] }
chrono = { version = "0.4", default-features = false }
clap = { version = "4.5", features = ["derive"] }
glob = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
rand = { version = "0.9", features = ["std", "std_rng", "thread_rng"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["std"] }
subprocess = "0.2"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"], default-features = false }
toml = "0.9"
uuid = { version = "1.19", features = ["v4"], default-features = false }
pg_impl = { path = "./pg_impl" }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "runtime-tokio", "migrate", "chrono", "uuid", "macros"], default-features = false }
flate2 = "1.1"
tar = "0.4"
reqwest = "0.13"
pkg-manage-util = { git = "https://github.com/CachyOS/pkg-manage-util", rev = "927a956671108268d252523d6a0764e7cff6d969", version = "0.1.0" }

[dev-dependencies]
tempfile = "3.27"
zstd = { version = "0.13", features = ["thin"], default-features = false }
assert_cmd = "2.2"

[profile.release]
strip = "symbols"
panic = "abort"
lto = true
opt-level = 3
codegen-units = 1
