server-name: dashboard-api-service 1.0
logger-level: info

server-port: 5862

testsuite-enabled: false
enabled-without-testsuite: true

db-connection: 'postgresql://user:1234@localhost:5432/pg_repomanage'

secdist-path: secure_data.json
config-fallback: dynamic_config_fallback.json
