server-name: dashboard-api-service 1.0
logger-level: info

server-port: 5862

testsuite-enabled: false

db-connection: 'postgresql://user:1234@localhost:5432/pg_repomanage'

config-fallback: dynamic_config_fallback.json
