server-name: dashboard-api-service 1.0
logger-level: error

server-port: 5862

testsuite-enabled: false

db-connection: 'postgresql://user:1234@repo-postgres:5432/pg_repomanage'

secdist-path: secure_data.json
config-fallback: dynamic_config_fallback.json
