server-name: dashboard-api-service 1.0
logger-level: debug

server-port: 5862

testsuite-enabled: true

db-connection: 'postgresql://testsuite@repo-postgres:15433/pg_repomanage'

config-fallback: dynamic_config_fallback.json
