global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: userver
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "api-postgresql-service:8086"

  - job_name: "redis_exporter_targets"
    static_configs:
      - targets:
          - redis://valkey-primary:6379
          - redis://valkey-replica:6379
          - redis://valkey-sentinel:26379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  - job_name: "redis_exporter"
    static_configs:
      - targets:
          - redis-exporter:9121
